// Code generated by MockGen. DO NOT EDIT.
// Source: go.inout.gg/shield/shielduser (interfaces: Authenticator)
//
// Generated by this command:
//
//	mockgen -destination=../internal/mocks/authenticator_mock.go -package=mocks -typed . Authenticator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	shielduser "go.inout.gg/shield/shielduser"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthenticator is a mock of Authenticator interface.
type MockAuthenticator[U any, S any] struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorMockRecorder[U, S]
	isgomock struct{}
}

// MockAuthenticatorMockRecorder is the mock recorder for MockAuthenticator.
type MockAuthenticatorMockRecorder[U any, S any] struct {
	mock *MockAuthenticator[U, S]
}

// NewMockAuthenticator creates a new mock instance.
func NewMockAuthenticator[U any, S any](ctrl *gomock.Controller) *MockAuthenticator[U, S] {
	mock := &MockAuthenticator[U, S]{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorMockRecorder[U, S]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticator[U, S]) EXPECT() *MockAuthenticatorMockRecorder[U, S] {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockAuthenticator[U, S]) Authenticate(arg0 http.ResponseWriter, arg1 *http.Request) (shielduser.Session[S], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", arg0, arg1)
	ret0, _ := ret[0].(shielduser.Session[S])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockAuthenticatorMockRecorder[U, S]) Authenticate(arg0, arg1 any) *MockAuthenticatorAuthenticateCall[U, S] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockAuthenticator[U, S])(nil).Authenticate), arg0, arg1)
	return &MockAuthenticatorAuthenticateCall[U, S]{Call: call}
}

// MockAuthenticatorAuthenticateCall wrap *gomock.Call
type MockAuthenticatorAuthenticateCall[U any, S any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthenticatorAuthenticateCall[U, S]) Return(arg0 shielduser.Session[S], arg1 error) *MockAuthenticatorAuthenticateCall[U, S] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthenticatorAuthenticateCall[U, S]) Do(f func(http.ResponseWriter, *http.Request) (shielduser.Session[S], error)) *MockAuthenticatorAuthenticateCall[U, S] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthenticatorAuthenticateCall[U, S]) DoAndReturn(f func(http.ResponseWriter, *http.Request) (shielduser.Session[S], error)) *MockAuthenticatorAuthenticateCall[U, S] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ExpireSessions mocks base method.
func (m *MockAuthenticator[U, S]) ExpireSessions(arg0 context.Context, arg1 pgx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireSessions", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExpireSessions indicates an expected call of ExpireSessions.
func (mr *MockAuthenticatorMockRecorder[U, S]) ExpireSessions(arg0, arg1 any) *MockAuthenticatorExpireSessionsCall[U, S] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireSessions", reflect.TypeOf((*MockAuthenticator[U, S])(nil).ExpireSessions), arg0, arg1)
	return &MockAuthenticatorExpireSessionsCall[U, S]{Call: call}
}

// MockAuthenticatorExpireSessionsCall wrap *gomock.Call
type MockAuthenticatorExpireSessionsCall[U any, S any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthenticatorExpireSessionsCall[U, S]) Return(arg0 error) *MockAuthenticatorExpireSessionsCall[U, S] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthenticatorExpireSessionsCall[U, S]) Do(f func(context.Context, pgx.Tx) error) *MockAuthenticatorExpireSessionsCall[U, S] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthenticatorExpireSessionsCall[U, S]) DoAndReturn(f func(context.Context, pgx.Tx) error) *MockAuthenticatorExpireSessionsCall[U, S] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Issue mocks base method.
func (m *MockAuthenticator[U, S]) Issue(arg0 http.ResponseWriter, arg1 *http.Request, arg2 shielduser.User[U]) (shielduser.Session[S], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issue", arg0, arg1, arg2)
	ret0, _ := ret[0].(shielduser.Session[S])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Issue indicates an expected call of Issue.
func (mr *MockAuthenticatorMockRecorder[U, S]) Issue(arg0, arg1, arg2 any) *MockAuthenticatorIssueCall[U, S] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MockAuthenticator[U, S])(nil).Issue), arg0, arg1, arg2)
	return &MockAuthenticatorIssueCall[U, S]{Call: call}
}

// MockAuthenticatorIssueCall wrap *gomock.Call
type MockAuthenticatorIssueCall[U any, S any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthenticatorIssueCall[U, S]) Return(arg0 shielduser.Session[S], arg1 error) *MockAuthenticatorIssueCall[U, S] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthenticatorIssueCall[U, S]) Do(f func(http.ResponseWriter, *http.Request, shielduser.User[U]) (shielduser.Session[S], error)) *MockAuthenticatorIssueCall[U, S] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthenticatorIssueCall[U, S]) DoAndReturn(f func(http.ResponseWriter, *http.Request, shielduser.User[U]) (shielduser.Session[S], error)) *MockAuthenticatorIssueCall[U, S] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
