// Code generated by MockGen. DO NOT EDIT.
// Source: go.inout.gg/shield/shielduser (interfaces: Impersonator)
//
// Generated by this command:
//
//	mockgen -destination=../internal/mocks/impersonator_mock.go -package=mocks -typed . Impersonator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	shielduser "go.inout.gg/shield/shielduser"
	gomock "go.uber.org/mock/gomock"
)

// MockImpersonator is a mock of Impersonator interface.
type MockImpersonator[U any, S any] struct {
	ctrl     *gomock.Controller
	recorder *MockImpersonatorMockRecorder[U, S]
	isgomock struct{}
}

// MockImpersonatorMockRecorder is the mock recorder for MockImpersonator.
type MockImpersonatorMockRecorder[U any, S any] struct {
	mock *MockImpersonator[U, S]
}

// NewMockImpersonator creates a new mock instance.
func NewMockImpersonator[U any, S any](ctrl *gomock.Controller) *MockImpersonator[U, S] {
	mock := &MockImpersonator[U, S]{ctrl: ctrl}
	mock.recorder = &MockImpersonatorMockRecorder[U, S]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImpersonator[U, S]) EXPECT() *MockImpersonatorMockRecorder[U, S] {
	return m.recorder
}

// Impersonate mocks base method.
func (m *MockImpersonator[U, S]) Impersonate(arg0 http.ResponseWriter, arg1 *http.Request, arg2 *shielduser.Session[S], arg3 *shielduser.User[U]) (*shielduser.Session[S], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Impersonate", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*shielduser.Session[S])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Impersonate indicates an expected call of Impersonate.
func (mr *MockImpersonatorMockRecorder[U, S]) Impersonate(arg0, arg1, arg2, arg3 any) *MockImpersonatorImpersonateCall[U, S] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Impersonate", reflect.TypeOf((*MockImpersonator[U, S])(nil).Impersonate), arg0, arg1, arg2, arg3)
	return &MockImpersonatorImpersonateCall[U, S]{Call: call}
}

// MockImpersonatorImpersonateCall wrap *gomock.Call
type MockImpersonatorImpersonateCall[U any, S any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImpersonatorImpersonateCall[U, S]) Return(arg0 *shielduser.Session[S], arg1 error) *MockImpersonatorImpersonateCall[U, S] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImpersonatorImpersonateCall[U, S]) Do(f func(http.ResponseWriter, *http.Request, *shielduser.Session[S], *shielduser.User[U]) (*shielduser.Session[S], error)) *MockImpersonatorImpersonateCall[U, S] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImpersonatorImpersonateCall[U, S]) DoAndReturn(f func(http.ResponseWriter, *http.Request, *shielduser.Session[S], *shielduser.User[U]) (*shielduser.Session[S], error)) *MockImpersonatorImpersonateCall[U, S] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
