// Code generated by MockGen. DO NOT EDIT.
// Source: go.inout.gg/shield/shieldpassword (interfaces: PasswordChecker)
//
// Generated by this command:
//
//	mockgen -destination=../internal/mocks/password_checker_mock.go -package=mocks . PasswordChecker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPasswordChecker is a mock of PasswordChecker interface.
type MockPasswordChecker struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordCheckerMockRecorder
	isgomock struct{}
}

// MockPasswordCheckerMockRecorder is the mock recorder for MockPasswordChecker.
type MockPasswordCheckerMockRecorder struct {
	mock *MockPasswordChecker
}

// NewMockPasswordChecker creates a new mock instance.
func NewMockPasswordChecker(ctrl *gomock.Controller) *MockPasswordChecker {
	mock := &MockPasswordChecker{ctrl: ctrl}
	mock.recorder = &MockPasswordCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordChecker) EXPECT() *MockPasswordCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockPasswordChecker) Check(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockPasswordCheckerMockRecorder) Check(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockPasswordChecker)(nil).Check), arg0, arg1)
}
