pre-commit:
  parallel: true
  jobs:
    - name: typos
      run: typos
    - name: lint & test
      glob: "*.go"
      group:
        jobs:
          - glob: "*.go"
            run: just lint-fix
          - glob: "*.go"
            run: just test-all
    # - name: format SQL
    #   glob: "*.sql"
    #   run: just format-sql
