// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package dbsqlc

import (
	"context"
)

// iteratorForCreateRecoveryCodeBatch implements pgx.CopyFromSource.
type iteratorForCreateRecoveryCodeBatch struct {
	rows                 []CreateRecoveryCodeBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateRecoveryCodeBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateRecoveryCodeBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].UserID,
		r.rows[0].RecoveryCodeHash,
		r.rows[0].IsConsumable,
	}, nil
}

func (r iteratorForCreateRecoveryCodeBatch) Err() error {
	return nil
}

func (q *Queries) CreateRecoveryCodeBatch(ctx context.Context, db DBTX, arg []CreateRecoveryCodeBatchParams) (int64, error) {
	return db.CopyFrom(ctx, []string{"shield_recovery_codes"}, []string{"id", "user_id", "recovery_code_hash", "is_consumable"}, &iteratorForCreateRecoveryCodeBatch{rows: arg})
}
