// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"time"
)

type ShieldPasswordResetToken struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	IsUsed    bool
	Token     string
	ExpiresAt time.Time
	UserID    int64
}

type ShieldRecoveryCode struct {
	ID               int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
	UserID           int64
	RecoveryCodeHash string
	IsConsumable     bool
	EvictedBy        *int64
	EvictedAt        time.Time
}

type ShieldUser struct {
	ID              int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Email           string
	IsEmailVerified bool
}

type ShieldUserCredential struct {
	ID                   int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Name                 string
	UserID               int64
	UserCredentialKey    string
	UserCredentialSecret string
}

type ShieldUserEmailVerificationToken struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	IsUsed    bool
	Token     string
	Email     string
	UserID    int64
}

type ShieldUserMfa struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	UserID    int64
}

type ShieldUserSession struct {
	ID            int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ExpiresAt     time.Time
	UserID        int64
	EvictedBy     *int64
	IsMfaRequired bool
}

type ShieldWorkspace struct {
	ID        int64
	OwnedBy   int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Slug      string
}

type ShieldWorkspaceMembershipInvitation struct {
	ID          int64
	WorkspaceID int64
	TeamID      int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	MemberEmail string
	Status      string
	ExpiresAt   time.Time
	AcceptedAt  time.Time
	RejectedAt  time.Time
}

type ShieldWorkspaceTeam struct {
	ID          int64
	WorkspaceID int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	IsSystem    bool
	Name        string
	Handle      string
	Metadata    []byte
}

type ShieldWorkspaceTeamMember struct {
	ID          int64
	WorkspaceID int64
	TeamID      int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	MemberID    int64
}
