// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbsqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ShieldPasswordResetToken struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	IsUsed    bool
	Token     string
	ExpiresAt time.Time
	UserID    uuid.UUID
}

type ShieldRecoveryCode struct {
	ID               uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	UserID           uuid.UUID
	RecoveryCodeHash string
	IsConsumable     bool
	EvictedBy        uuid.UUID
	EvictedAt        pgtype.Timestamptz
}

type ShieldUser struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Email           string
	IsEmailVerified bool
}

type ShieldUserCredential struct {
	ID                   uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Name                 string
	UserID               uuid.UUID
	UserCredentialKey    string
	UserCredentialSecret string
}

type ShieldUserEmailVerificationToken struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	IsUsed    bool
	Token     string
	Email     string
	UserID    uuid.UUID
}

type ShieldUserSession struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	UserID    uuid.UUID
	EvictedBy uuid.UUID
}
