// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"time"

	typeid "go.jetify.com/typeid/v2"
)

type ShieldPasswordResetToken struct {
	ID        typeid.TypeID
	CreatedAt time.Time
	UpdatedAt time.Time
	IsUsed    bool
	Token     string
	ExpiresAt time.Time
	UserID    typeid.TypeID
}

type ShieldRecoveryCode struct {
	ID               typeid.TypeID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	UserID           typeid.TypeID
	RecoveryCodeHash string
	IsConsumable     bool
	EvictedBy        *typeid.TypeID
	EvictedAt        time.Time
}

type ShieldUser struct {
	ID              typeid.TypeID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Email           string
	IsEmailVerified bool
}

type ShieldUserCredential struct {
	ID                   typeid.TypeID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Name                 string
	UserID               typeid.TypeID
	UserCredentialKey    string
	UserCredentialSecret string
}

type ShieldUserEmailVerificationToken struct {
	ID        typeid.TypeID
	CreatedAt time.Time
	UpdatedAt time.Time
	IsUsed    bool
	Token     string
	Email     string
	UserID    typeid.TypeID
}

type ShieldUserMfa struct {
	ID        typeid.TypeID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	UserID    typeid.TypeID
}

type ShieldUserSession struct {
	ID            typeid.TypeID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ExpiresAt     time.Time
	UserID        typeid.TypeID
	EvictedBy     *typeid.TypeID
	IsMfaRequired bool
}

type ShieldWorkspace struct {
	ID        typeid.TypeID
	OwnedBy   typeid.TypeID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Slug      string
}

type ShieldWorkspaceMembershipInvitation struct {
	ID          typeid.TypeID
	WorkspaceID typeid.TypeID
	TeamID      typeid.TypeID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	MemberEmail string
	Status      string
	ExpiresAt   time.Time
	AcceptedAt  time.Time
	RejectedAt  time.Time
}

type ShieldWorkspaceTeam struct {
	ID          typeid.TypeID
	WorkspaceID typeid.TypeID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	IsSystem    bool
	Name        string
	Handle      string
	Metadata    []byte
}

type ShieldWorkspaceTeamMember struct {
	ID          string
	WorkspaceID string
	TeamID      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	MemberID    string
}
