// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: recovery_code_query.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
)

type CreateRecoveryCodeBatchParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RecoveryCodeHash string
	IsConsumable     bool
}

const evictUnconsumedRecoveryCodeBatch = `-- name: EvictUnconsumedRecoveryCodeBatch :exec
UPDATE shield_recovery_codes
SET
  evicted_by = $1::UUID,
  evicted_at = NOW()
WHERE user_id = $2 AND is_consumable = TRUE
`

type EvictUnconsumedRecoveryCodeBatchParams struct {
	EvictedBy uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) EvictUnconsumedRecoveryCodeBatch(ctx context.Context, db DBTX, arg EvictUnconsumedRecoveryCodeBatchParams) error {
	_, err := db.Exec(ctx, evictUnconsumedRecoveryCodeBatch, arg.EvictedBy, arg.UserID)
	return err
}
