// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: recovery_code_query.sql

package dbsqlc

import (
	"context"

	typeid "go.jetify.com/typeid/v2"
)

type CreateRecoveryCodeBatchParams struct {
	ID               typeid.TypeID
	UserID           typeid.TypeID
	RecoveryCodeHash string
	IsConsumable     bool
}

const evictUnconsumedRecoveryCodeBatch = `-- name: EvictUnconsumedRecoveryCodeBatch :exec
UPDATE shield_recovery_codes
SET
  evicted_by = $1,
  evicted_at = NOW()
WHERE user_id = $2 AND is_consumable = TRUE
`

type EvictUnconsumedRecoveryCodeBatchParams struct {
	EvictedBy *typeid.TypeID
	UserID    typeid.TypeID
}

func (q *Queries) EvictUnconsumedRecoveryCodeBatch(ctx context.Context, db DBTX, arg EvictUnconsumedRecoveryCodeBatchParams) error {
	_, err := db.Exec(ctx, evictUnconsumedRecoveryCodeBatch, arg.EvictedBy, arg.UserID)
	return err
}
