// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_query.sql

package dbsqlc

import (
	"context"
	"time"
)

const allActiveSessions = `-- name: AllActiveSessions :many
SELECT id, created_at, updated_at, expires_at, user_id, evicted_by, is_mfa_required
FROM shield_user_sessions
WHERE user_id = $1 AND expires_at > NOW()
`

func (q *Queries) AllActiveSessions(ctx context.Context, db DBTX, userID int64) ([]ShieldUserSession, error) {
	rows, err := db.Query(ctx, allActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShieldUserSession
	for rows.Next() {
		var i ShieldUserSession
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.UserID,
			&i.EvictedBy,
			&i.IsMfaRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO shield_user_sessions (user_id, expires_at, is_mfa_required)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateUserSessionParams struct {
	UserID        int64
	ExpiresAt     time.Time
	IsMfaRequired bool
}

func (q *Queries) CreateUserSession(ctx context.Context, db DBTX, arg CreateUserSessionParams) (int64, error) {
	row := db.QueryRow(ctx, createUserSession, arg.UserID, arg.ExpiresAt, arg.IsMfaRequired)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const expireAllSessionsByUserID = `-- name: ExpireAllSessionsByUserID :many
UPDATE shield_user_sessions
SET
  expires_at = NOW(),
  evicted_by = $1
WHERE user_id = $2
RETURNING id
`

type ExpireAllSessionsByUserIDParams struct {
	EvictedBy *int64
	UserID    int64
}

func (q *Queries) ExpireAllSessionsByUserID(ctx context.Context, db DBTX, arg ExpireAllSessionsByUserIDParams) ([]int64, error) {
	rows, err := db.Query(ctx, expireAllSessionsByUserID, arg.EvictedBy, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireSessionByID = `-- name: ExpireSessionByID :one
UPDATE shield_user_sessions
SET expires_at = NOW()
WHERE id = $1
RETURNING id
`

func (q *Queries) ExpireSessionByID(ctx context.Context, db DBTX, id int64) (int64, error) {
	row := db.QueryRow(ctx, expireSessionByID, id)
	err := row.Scan(&id)
	return id, err
}

const expireSomeSessionsByUserID = `-- name: ExpireSomeSessionsByUserID :many
UPDATE shield_user_sessions
SET
  expires_at = NOW(),
  evicted_by = $1
WHERE user_id = $2 AND id != ANY ($3::BIGINT[])
RETURNING id
`

type ExpireSomeSessionsByUserIDParams struct {
	EvictedBy  *int64
	UserID     int64
	SessionIds []int64
}

func (q *Queries) ExpireSomeSessionsByUserID(ctx context.Context, db DBTX, arg ExpireSomeSessionsByUserIDParams) ([]int64, error) {
	rows, err := db.Query(ctx, expireSomeSessionsByUserID, arg.EvictedBy, arg.UserID, arg.SessionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findActiveSessionByID = `-- name: FindActiveSessionByID :one
SELECT id, created_at, updated_at, expires_at, user_id, evicted_by, is_mfa_required
FROM shield_user_sessions
WHERE id = $1 AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) FindActiveSessionByID(ctx context.Context, db DBTX, id int64) (ShieldUserSession, error) {
	row := db.QueryRow(ctx, findActiveSessionByID, id)
	var i ShieldUserSession
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.UserID,
		&i.EvictedBy,
		&i.IsMfaRequired,
	)
	return i, err
}
