// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_query.sql

package dbsqlc

import (
	"context"
	"time"
)

const acceptWorkspaceInvitation = `-- name: AcceptWorkspaceInvitation :exec
UPDATE shield_workspace_membership_invitations
SET status = 'accepted', accepted_at = NOW(), expires_at = NOW()
WHERE id = $1
`

func (q *Queries) AcceptWorkspaceInvitation(ctx context.Context, db DBTX, invitationID int64) error {
	_, err := db.Exec(ctx, acceptWorkspaceInvitation, invitationID)
	return err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO shield_workspace_teams (workspace_id, name, handle, metadata, is_system)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateTeamParams struct {
	WorkspaceID int64
	Name        string
	Handle      string
	Metadata    []byte
	IsSystem    bool
}

func (q *Queries) CreateTeam(ctx context.Context, db DBTX, arg CreateTeamParams) (int64, error) {
	row := db.QueryRow(ctx, createTeam,
		arg.WorkspaceID,
		arg.Name,
		arg.Handle,
		arg.Metadata,
		arg.IsSystem,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO shield_workspaces (owned_by, name)
VALUES ($1, $2)
RETURNING id
`

type CreateWorkspaceParams struct {
	OwnedBy int64
	Name    string
}

func (q *Queries) CreateWorkspace(ctx context.Context, db DBTX, arg CreateWorkspaceParams) (int64, error) {
	row := db.QueryRow(ctx, createWorkspace, arg.OwnedBy, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findWorkspaceByID = `-- name: FindWorkspaceByID :one
SELECT id, owned_by, created_at, updated_at, name, slug
FROM shield_workspaces
WHERE id = $1
`

func (q *Queries) FindWorkspaceByID(ctx context.Context, db DBTX, id int64) (ShieldWorkspace, error) {
	row := db.QueryRow(ctx, findWorkspaceByID, id)
	var i ShieldWorkspace
	err := row.Scan(
		&i.ID,
		&i.OwnedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Slug,
	)
	return i, err
}

const inviteUserToWorkspaceByEmail = `-- name: InviteUserToWorkspaceByEmail :exec
INSERT INTO shield_workspace_membership_invitations (workspace_id, team_id, member_email, expires_at)
VALUES ($1, $2, $3, $4)
`

type InviteUserToWorkspaceByEmailParams struct {
	WorkspaceID int64
	TeamID      int64
	MemberEmail string
	ExpiresAt   time.Time
}

func (q *Queries) InviteUserToWorkspaceByEmail(ctx context.Context, db DBTX, arg InviteUserToWorkspaceByEmailParams) error {
	_, err := db.Exec(ctx, inviteUserToWorkspaceByEmail,
		arg.WorkspaceID,
		arg.TeamID,
		arg.MemberEmail,
		arg.ExpiresAt,
	)
	return err
}

const rejectWorkspaceInvitation = `-- name: RejectWorkspaceInvitation :exec
UPDATE shield_workspace_membership_invitations
SET status = 'rejected', rejected_at = NOW(), expires_at = NOW()
WHERE id = $1
`

func (q *Queries) RejectWorkspaceInvitation(ctx context.Context, db DBTX, invitationID int64) error {
	_, err := db.Exec(ctx, rejectWorkspaceInvitation, invitationID)
	return err
}

const transferWorkspaceOwnership = `-- name: TransferWorkspaceOwnership :exec
UPDATE shield_workspaces
SET owned_by = $1
WHERE id = $2
`

type TransferWorkspaceOwnershipParams struct {
	NewOwnerID  int64
	WorkspaceID int64
}

func (q *Queries) TransferWorkspaceOwnership(ctx context.Context, db DBTX, arg TransferWorkspaceOwnershipParams) error {
	_, err := db.Exec(ctx, transferWorkspaceOwnership, arg.NewOwnerID, arg.WorkspaceID)
	return err
}
