// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbsqlctest

import (
	"time"
)

type ShieldPasswordResetToken struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsUsed    bool
	Token     string
	ExpiresAt time.Time
	UserID    string
}

type ShieldRecoveryCode struct {
	ID               string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	UserID           string
	RecoveryCodeHash string
	IsConsumable     bool
	EvictedBy        *string
	EvictedAt        time.Time
}

type ShieldUser struct {
	ID              string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Email           string
	IsEmailVerified bool
}

type ShieldUserCredential struct {
	ID                   string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Name                 string
	UserID               string
	UserCredentialKey    string
	UserCredentialSecret string
}

type ShieldUserEmailVerificationToken struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsUsed    bool
	Token     string
	Email     string
	UserID    string
}

type ShieldUserMfa struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	UserID    string
}

type ShieldUserSession struct {
	ID            string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ExpiresAt     time.Time
	UserID        string
	EvictedBy     *string
	IsMfaRequired bool
}
