// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlctest

import (
	"context"

	typeid "go.jetify.com/typeid/v2"
)

type Querier interface {
	CreateUserMFA(ctx context.Context, db DBTX, arg CreateUserMFAParams) (ShieldUserMfa, error)
	GetUserMFAsByUserID(ctx context.Context, db DBTX, userID typeid.TypeID) ([]ShieldUserMfa, error)
	TestCreatePassword(ctx context.Context, db DBTX, arg TestCreatePasswordParams) (ShieldUserCredential, error)
	TestCreateUser(ctx context.Context, db DBTX, arg TestCreateUserParams) (ShieldUser, error)
	TestFindAllUsers(ctx context.Context, db DBTX) ([]ShieldUser, error)
	TestFindUserByID(ctx context.Context, db DBTX, id typeid.TypeID) (ShieldUser, error)
}

var _ Querier = (*Queries)(nil)
